# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Artefactos.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Artefactos_Endoscopia(object):
    def setupUi(self, Artefactos_Endoscopia):
        Artefactos_Endoscopia.setObjectName("Artefactos_Endoscopia")
        Artefactos_Endoscopia.setStyleSheet("background-color: rgb(231, 236, 255);\n"
"background-color: rgb(175, 175, 175);")
        self.centralwidget = QtWidgets.QWidget(Artefactos_Endoscopia)
        self.centralwidget.setObjectName("centralwidget")
        self.Examinar = QtWidgets.QPushButton(self.centralwidget)
        self.Examinar.setGeometry(QtCore.QRect(90, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.Examinar.setFont(font)
        self.Examinar.setStyleSheet("background-color: rgb(102, 102, 102);")
        self.Examinar.setObjectName("Examinar")
        self.Analizar = QtWidgets.QPushButton(self.centralwidget)
        self.Analizar.setGeometry(QtCore.QRect(70, 400, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.Analizar.setFont(font)
        self.Analizar.setStyleSheet("background-color: rgb(102, 102, 102);")
        self.Analizar.setObjectName("Analizar")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(400, 200, 171, 121))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(177, 177, 177);")
        self.textEdit.setObjectName("textEdit")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(820, 380, 160, 22))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(740, 380, 71, 17))
        self.radioButton.setObjectName("radioButton")
        self.automatica = QtWidgets.QRadioButton(self.centralwidget)
        self.automatica.setGeometry(QtCore.QRect(650, 380, 81, 17))
        self.automatica.setObjectName("automatica")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 370, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 351, 291))
        self.label_2.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 80, 351, 291))
        self.label_3.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 150, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Corregir = QtWidgets.QPushButton(self.centralwidget)
        self.Corregir.setGeometry(QtCore.QRect(680, 410, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.Corregir.setFont(font)
        self.Corregir.setStyleSheet("background-color: rgb(102, 102, 102);")
        self.Corregir.setObjectName("Corregir")
        self.popup = QtWidgets.QComboBox(self.centralwidget)
        self.popup.setGeometry(QtCore.QRect(950, 200, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.popup.setFont(font)
        self.popup.setObjectName("popup")
        self.popup.addItem("")
        self.popup.setItemText(0, "")
        self.popup.addItem("")
        self.popup.addItem("")
        self.popup.addItem("")
        self.popup.addItem("")
        self.popup.addItem("")
        self.popup.setItemText(5, "")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1040, 250, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(102, 102, 102);")
        self.pushButton.setObjectName("pushButton")
        self.popup_DM = QtWidgets.QComboBox(self.centralwidget)
        self.popup_DM.setGeometry(QtCore.QRect(950, 200, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.popup_DM.setFont(font)
        self.popup_DM.setObjectName("popup_DM")
        self.popup_DM.addItem("")
        self.popup_DM.setItemText(0, "")
        self.popup_DM.addItem("")
        self.popup_DM.addItem("")
        self.popup_DM.addItem("")
        self.popup_NO = QtWidgets.QComboBox(self.centralwidget)
        self.popup_NO.setGeometry(QtCore.QRect(950, 200, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.popup_NO.setFont(font)
        self.popup_NO.setObjectName("popup_NO")
        self.popup_NO.addItem("")
        self.popup_NO.setItemText(0, "")
        self.popup_NO.addItem("")
        self.popup_NO.addItem("")
        self.popup_NO.addItem("")
        self.popup_NO.setItemText(3, "")
        self.popup_DOS = QtWidgets.QComboBox(self.centralwidget)
        self.popup_DOS.setGeometry(QtCore.QRect(950, 200, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.popup_DOS.setFont(font)
        self.popup_DOS.setObjectName("popup_DOS")
        self.popup_DOS.addItem("")
        self.popup_DOS.setItemText(0, "")
        self.popup_DOS.addItem("")
        self.popup_DOS.addItem("")
        self.popup_DOS.addItem("")
        self.popup_DOS.addItem("")
        self.popup_DOS.addItem("")
        self.Examinar.raise_()
        self.Analizar.raise_()
        self.textEdit.raise_()
        self.horizontalSlider.raise_()
        self.radioButton.raise_()
        self.automatica.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.popup.raise_()
        self.pushButton.raise_()
        self.popup_DM.raise_()
        self.Corregir.raise_()
        self.popup_NO.raise_()
        self.popup_DOS.raise_()
        Artefactos_Endoscopia.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Artefactos_Endoscopia)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1223, 21))
        self.menubar.setObjectName("menubar")
        Artefactos_Endoscopia.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Artefactos_Endoscopia)
        self.statusbar.setObjectName("statusbar")
        Artefactos_Endoscopia.setStatusBar(self.statusbar)

        self.retranslateUi(Artefactos_Endoscopia)
        QtCore.QMetaObject.connectSlotsByName(Artefactos_Endoscopia)

    def retranslateUi(self, Artefactos_Endoscopia):
        _translate = QtCore.QCoreApplication.translate
        Artefactos_Endoscopia.setWindowTitle(_translate("Artefactos_Endoscopia", "MainWindow"))
        self.Examinar.setText(_translate("Artefactos_Endoscopia", "Examinar"))
        self.Analizar.setText(_translate("Artefactos_Endoscopia", "Analizar imagen"))
        self.textEdit.setHtml(_translate("Artefactos_Endoscopia", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.radioButton.setText(_translate("Artefactos_Endoscopia", "Manual"))
        self.automatica.setText(_translate("Artefactos_Endoscopia", "Automatica"))
        self.label.setText(_translate("Artefactos_Endoscopia", "Corrección"))
        self.label_4.setText(_translate("Artefactos_Endoscopia", "Se detectaron:"))
        self.Corregir.setText(_translate("Artefactos_Endoscopia", "Corregir"))
        self.popup.setItemText(1, _translate("Artefactos_Endoscopia", "Guardar imagen original"))
        self.popup.setItemText(2, _translate("Artefactos_Endoscopia", "Guardar imagen corregida"))
        self.popup.setItemText(3, _translate("Artefactos_Endoscopia", "Guardar imagen sin etiquetas"))
        self.popup.setItemText(4, _translate("Artefactos_Endoscopia", "Descargar mascara binaria de RE"))
        self.pushButton.setText(_translate("Artefactos_Endoscopia", "ok"))
        self.popup_DM.setItemText(1, _translate("Artefactos_Endoscopia", "Guardar imagen original"))
        self.popup_DM.setItemText(2, _translate("Artefactos_Endoscopia", "Guardar imagen sin etiquetas"))
        self.popup_DM.setItemText(3, _translate("Artefactos_Endoscopia", "Eliminar imagen"))
        self.popup_NO.setItemText(1, _translate("Artefactos_Endoscopia", "Guardar imagen original"))
        self.popup_NO.setItemText(2, _translate("Artefactos_Endoscopia", "Guardar imagen sin etiquetas"))
        self.popup_DOS.setItemText(1, _translate("Artefactos_Endoscopia", "Guardar imagen original"))
        self.popup_DOS.setItemText(2, _translate("Artefactos_Endoscopia", "Guardar imagen corregida"))
        self.popup_DOS.setItemText(3, _translate("Artefactos_Endoscopia", "Guardar imagen sin etiquetas"))
        self.popup_DOS.setItemText(4, _translate("Artefactos_Endoscopia", "Descargar mascara binaria de RE"))
        self.popup_DOS.setItemText(5, _translate("Artefactos_Endoscopia", "Eliminar imagen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Artefactos_Endoscopia = QtWidgets.QMainWindow()
    ui = Ui_Artefactos_Endoscopia()
    ui.setupUi(Artefactos_Endoscopia)
    Artefactos_Endoscopia.show()
    sys.exit(app.exec_())

